f

diff --git a/.github/workflows/pragma-windows-ci.yml b/.github/workflows/pragma-windows-ci.yml
--- a/.github/workflows/pragma-windows-ci.yml
+++ b/.github/workflows/pragma-windows-ci.yml
@@ -34,39 +34,39 @@ jobs:
         Invoke-WebRequest -Uri "https://github.com/Silverlan/pragma/releases/download/nightly/pragma-win64.zip" -OutFile "pragma-win64.zip"
         Expand-Archive -Path "pragma-win64.zip" -DestinationPath "pragma"
 
-    - name: Run Test Scripts
-      shell: pwsh
-      run: |
-        Set-Location -Path "pragma"
-        ./pragma_server -luaext -log 2 2 +map "test_physics" +"lua_exec tests/ci_runner_tests.lua"
-        $EXIT_CODE = $LASTEXITCODE
-        # Check the exit code
-        if ($EXIT_CODE -eq 0) {
-          Write-Output "Tests were successful."
-        }
-        else {
-          Write-Output "Tests have failed with exit code $EXIT_CODE."
-          exit 1 # Exit the step with an error status
-        }
+    #- name: Run Test Scripts
+    #  shell: pwsh
+    #  run: |
+    #    Set-Location -Path "pragma"
+    #    ./pragma_server -luaext -log 2 2 +map "test_physics" +"lua_exec tests/ci_runner_tests.lua"
+    #    $EXIT_CODE = $LASTEXITCODE
+    #    # Check the exit code
+    #    if ($EXIT_CODE -eq 0) {
+    #      Write-Output "Tests were successful."
+    #    }
+    #    else {
+    #      Write-Output "Tests have failed with exit code $EXIT_CODE."
+    #      exit 1 # Exit the step with an error status
+    #    }
 
-    - name: Check Result
-      shell: bash
-      run: |
-        CI_CONTENTS=$(cat "pragma/ci.txt")
-        if [ $exit_code -ne 0 ]; then
-          exit $exit_code
-        fi
-        if [ "$CI_CONTENTS" == "0" ]; then
-          echo "ci.txt contains '0'. Step failed."
-          exit 1
-        fi
+    #- name: Check Result
+    #  shell: bash
+    #  run: |
+    #    CI_CONTENTS=$(cat "pragma/ci.txt")
+    #    if [ $exit_code -ne 0 ]; then
+    #      exit $exit_code
+    #    fi
+    #    if [ "$CI_CONTENTS" == "0" ]; then
+    #      echo "ci.txt contains '0'. Step failed."
+    #      exit 1
+    #    fi
 
-    - name: Upload Log
-      uses: actions/upload-artifact@v4
-      if: always()
-      with:
-        name: log_server
-        path: "pragma/log_server.txt"
+    #- name: Upload Log
+    #  uses: actions/upload-artifact@v4
+    #  if: always()
+    #  with:
+    #    name: log_server
+    #    path: "pragma/log_server.txt"
 
 
     - uses: mxschmitt/action-tmate@v3.18
